### ISSUE TITLE
The audiofx is not working

### ISSUE THREAD

**Issue by ghost** [ngoquang2708/android_device_samsung_vivalto3gvn#59] opened 2016-07-28 13:48 UTC
It says not available when using speaker while I actually plugged in the headset, how is that possible?

**Comment by ngoquang2708** [comment] 2016-07-28 13:56
Confirmed.

**Comment by diepquynh** [comment] 2016-07-28 14:00
@ngoquang2708 
This thing... I've reported a very long time ago, since CM11, but you said it's working LOL

**Comment by ngoquang2708** [comment] 2016-08-01 11:29
Fixed by https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/5be9eb1ae96cfa39011abe8a60ec04210697267a.

**Closed as completed by ngoquang2708** 2016-08-01 11:29 UTC
Labels: bug, cm-13.0
