### ISSUE TITLE
Camera not work with new source code

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#5] opened 2016-02-09 15:39 UTC

**Comment by diepquynh** [comment] 2016-04-01 23:37
Please close this, as it's working now

**Comment by ngoquang2708** [comment] 2016-04-02 10:26
Did you test it? I means compile the source codes, not use the blobs.

**Comment by diepquynh** [comment] 2016-04-02 11:58
Of course, because stock blobs causes "Cannot connect to camera" bug

**Comment by ngoquang2708** [comment] 2016-04-02 13:16
I don't know what you means. We ARE using stock blobs. I disabled the camera source already.

**Comment by diepquynh** [comment] 2016-04-02 13:59
Umm... in CM12.1 bro

**Comment by diepquynh** [comment] 2016-04-02 14:00
Ok, i think again
When compiling, i forgot to comment out the stock blob, so still unconfirmed now :D

**Comment by ngoquang2708** [comment] 2016-04-02 14:07
These lines

```
# Camera
PRODUCT_PACKAGES += \
    camera.scx15 \
    camera2.scx15
```

in `device_vivalto3gvn.mk` do nothing right now!

**Comment by diepquynh** [comment] 2016-04-02 14:10
Lots of compile error bro

**Comment by diepquynh** [comment] 2016-04-02 14:10
A real pain in the 4$$ fixing that

**Comment by ngoquang2708** [comment] 2016-04-02 14:11
Living with blobs for now. Trying fixing video.

**Comment by diepquynh** [comment] 2016-04-02 14:13
Btw, going to compile CM13
Not sure i have enough RAM or not to build the ROM with prebuilt chromium

**Comment by ngoquang2708** [comment] 2016-04-02 14:14
Search around to find someone compiled it :D

**Comment by diepquynh** [comment] 2016-04-02 14:20
Yeah, the prebuilt chromium

**Comment by diepquynh** [comment] 2016-07-31 13:24
I think, our sensor codes aren't in the camera source. Check logcat and you'll find it

**Closed as completed** 2018-06-05 10:54 UTC
Labels: wontfix, cm-13.0
