### ISSUE TITLE
cm-13.0: Screen flickering

### ISSUE THREAD

**Issue by diepquynh** [ngoquang2708/android_device_samsung_vivalto3gvn#46] opened 2016-06-14 18:31 UTC
Sometimes the phone does that, but with the affected apps only, even with disabled "Strict mode". Quick solution is tapping on recents button, then come back with the current opening app

**Comment by ngoquang2708** [comment] 2016-06-15 00:33
Confirmed.

**Comment by diepquynh** [comment] 2016-06-28 14:48
Now is this most annoying issue

**Comment by diepquynh** [comment] 2016-06-28 14:50
I guess CM13 developer options are broken

**Comment by ngoquang2708** [comment] 2016-06-28 14:56
Or our HALs are broken :)

**Comment by diepquynh** [comment] 2016-06-29 03:27
I guess again, gralloc's fault

**Comment by ngoquang2708** [comment] 2016-07-06 15:59
May be this commit will fix this issue https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/5b47381b39bf9be47ede313f7539004c5028b272.

**Comment by diepquynh** [comment] 2016-07-06 16:46
So, do we need to revert this? https://github.com/koquantam/android_frameworks_base/commit/1003c499017267bc497fc45cf8802cb933d9781b

**Comment by ngoquang2708** [comment] 2016-07-06 16:51
This Gerrit review http://review.cyanogenmod.org/#/c/125226/ is abandoned so we should not revert your mentioned commit. I just gave a ref from the i9300 device which has the same issue as us.

**Comment by ngoquang2708** [comment] 2016-07-07 03:11
I hasn't had any flickering since that change so I will close this issue.

**Closed as completed by ngoquang2708** 2016-07-07 03:11 UTC
Labels: cm-13.0

**Comment by diepquynh** [comment] 2016-07-07 03:17
Oh well, I would test so

**Comment by koquantam** [comment] 2016-07-07 03:17
But if I had, you have to open it again :D

**Comment by ngoquang2708** [comment] 2016-07-07 03:20
OK

2016-07-07 10:17 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-07 03:21
Anyway, do you plan making Nougat for our phone?

**Comment by ngoquang2708** [comment] 2016-07-07 03:27
I will wait until we have its source codes :)

2016-07-07 10:21 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-07 03:30
Yes, I'll wait too :D
Our country needs people like you

**Comment by diepquynh** [comment] 2016-07-07 03:57
Confirmed

**Comment by diepquynh** [comment] 2016-07-07 03:59
It's very nice that we don't face black preview recents like CM12.1 in CM13 anymore
And once again, one BoardConfig flag solves the problem o.O

**Comment by ngoquang2708** [comment] 2016-07-07 04:01
Codecs work great in CM13 with minor modification :)

2016-07-07 10:59 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-07 04:10
Actually, stock gralloc also does that change :v

**Comment by ngoquang2708** [comment] 2016-07-07 04:12
You mean the fix for ScreenRecording? I haven't found the root cause of
that issue yet.

2016-07-07 11:10 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-07 04:20
Yes, screen recording

**Comment by ngoquang2708** [comment] 2016-07-07 04:23
But that was fixed
https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/67ad84476b4044701a869c51582ae744bdd0fab2

2016-07-07 11:20 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-07 04:25
These HALs you took from `sp7715ga_gonk4.4_hemiao_mp` branch right?
So this is why it doesn't work with me

**Comment by ngoquang2708** [comment] 2016-07-07 04:26
Yes. Your board is sc8830, right?

2016-07-07 11:25 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-07 04:29
Yes. The `sprdroid4.4` branch works for me, except `gralloc`
It gives me an error, like `deleted function` which I never faced before

**Comment by ngoquang2708** [comment] 2016-07-07 04:34
Give me the compile error log, I could help if I can.

2016-07-07 11:29 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-07 04:41
Here
![screenshot from 2016-07-07 11 40 36](https://cloud.githubusercontent.com/assets/13411810/16642703/aaffa0d8-4437-11e6-9d93-7b7d063394ca.png)

**Comment by ngoquang2708** [comment] 2016-07-07 05:03
I know that bug, compare my gralloc framebuffer_device.cpp, you will see
the differences.

2016-07-07 11:41 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-07 05:17
Thanks bro. Now its usable

**Comment by diepquynh** [comment] 2016-07-07 13:35
Bro, I think we should switch all libs changes to vendor tree
Now we don't have same device anymore, but at least our devices has same SoC types that we can easily sync our changes on

**Comment by ngoquang2708** [comment] 2016-07-07 14:03
OK, I will plan it.

**Comment by ngoquang2708** [comment] 2016-07-07 14:11
But don't use my `android_vendor_sprd_open-source` tree. I just use it to view the history.
We should make `android_hardware_samsung_sprd-common` tree instead.

**Comment by diepquynh** [comment] 2016-07-07 14:12
Oh, you're right
But I've just pushed a commit on vendor tree for an hour :D

**Comment by ngoquang2708** [comment] 2016-07-07 14:14
I planed to fork @TeamButter `sprd-common` tree, but there are too many conflicts so I afraid of doing that :)

**Comment by diepquynh** [comment] 2016-07-07 14:16
Well most of their tree are for sc8810, while ours are scx15 and sc8830
But anyway, can we make separated folder for each SoC?

**Comment by ngoquang2708** [comment] 2016-07-07 14:24
Yes. And another tree `android_device_samsung_sprd-common`.

**Comment by diepquynh** [comment] 2016-07-07 15:22
Bro, I remember you've fixed wrong color with camera using H264 AVC codec
Can you locate me to that commit?

**Comment by ngoquang2708** [comment] 2016-07-07 15:30
https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/commit/245e30afc7fa164b0d1e356c8529c8f8d694b234

2016-07-07 22:22 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment] 2016-07-09 04:21
I've made a common hardware tree. Can you check it out and try using it?
